### ISSUE TITLE
How to use the Cancel() method?

### ISSUE THREAD

**Issue by jfongattw** [nradulovic/pyeds#10]
In the example code in readme.rst, how to stop the timer?

Best Regards,
Jach

**Comment by nradulovic** [comment]
Hello,

Please have a look the update README.rst if it is more clear now. Thanks.

Best regards,
Nenad

**Comment by nradulovic** [comment]
The README was updated with additional comments about timers. Feel free to reopen issue if it still is not clear. Thanks!
