### ISSUE TITLE
Release pyeds 17.12.1 to PyPI ?

### ISSUE THREAD

**Issue by kim-acmehi** [nradulovic/pyeds#12]
@nradulovic would you be so kind to tag and release the HEAD of pyeds master as version 17.12.1 to PyPI?  This is a great package and I have been using it since last October.  The only problem I found since 17.12.0 was the resource name check you have already fixed.  It would be nice if I could pull it from PyPI rather than my private repo.  Thanks in advance.

**Comment by nradulovic** [comment]
@kim-acmehi  Hello, thanks for pointing this up to me. I just forgot to push it to PyPI. I'll push the 20.9.0 version to pypi in a moment.

**Comment by nradulovic** [comment]
If you still have a problem feel free to create a new issue. Thanks!
